apiVersion: apps/v1
kind: Deployment
metadata:
  name: foo-deployment
  labels:
    app: foo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: foo
  template:
    metadata:
      labels:
        app: foo
    spec:
      containers:
      - name: foo
        image: wqd180067/http-echo
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        args: ["-listen=:80", "-text='foo'"]
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: bar-deployment
  labels:
    app: bar
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bar
  template:
    metadata:
      labels:
        app: bar
    spec:
      containers:
      - name: bar
        image: wqd180067/http-echo
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        args: ["-listen=:80", "-text='bar'"]
---

apiVersion: v1
kind: Service
metadata:
  name: foo
spec:
  type: NodePort
  selector:
    app: foo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30011
---

apiVersion: v1
kind: Service
metadata:
  name: bar
spec:
  type: NodePort
  selector:
    app: bar
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30012
---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: http-echo-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: "/foo"
        backend:
          service:
            name: foo
            port:
              number: 80
  - http:
      paths:
      - pathType: Prefix
        path: "/bar"
        backend:
          service:
            name: bar
            port:
              number: 80
