name: Makefile CI

on:
  push:
    branches: [ "master" , "github-actions"]
  pull_request:
    branches: [ "master" ]

env:
  BUILD_VERSION: 0.1

jobs:
  build-publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install Make
      run: make
      
    - name: Make build
      run: make build
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Build and push image to Docker Hub
      uses: docker/build-push-action@v3
      with:
        file: docker/alpine/Dockerfile
        context: .
        push: true
        tags: wqd180067/http-echo:${{ env.BUILD_VERSION }}.${{ github.run_number }}-${{ github.run_attempt }}

  update-kubernetes-manifest:
    needs: build-publish
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: yq - portable yaml processor
      uses: mikefarah/yq@v4.30.6

    - name: Update http-echo image version in kube manifest file
      run: |
        DOCKER_IMAGE_V=wqd180067/http-echo:${{ env.BUILD_VERSION }}.${{ github.run_number }}-${{ github.run_attempt }}
        IMAGE_V=$DOCKER_IMAGE_V yq -i '.spec.template.spec.containers[0].image = strenv(IMAGE_V)' kubernetes/http-echo/foo-deployment.yaml
        IMAGE_V=$DOCKER_IMAGE_V yq -i '.spec.template.spec.containers[0].image = strenv(IMAGE_V)' kubernetes/http-echo/bar-deployment.yaml

    - name: Pushes to another repository
      uses: cpina/github-action-push-to-another-repository@main
      env:
        SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source-directory: 'kubernetes'
        destination-github-username: 'D-Danesh'
        destination-repository-name: 'kubernetes-demo'
        user-email: d.danesh1993@gmail.com
        target-branch: main
        commit-message: http-echo image patched to ${{ env.BUILD_VERSION }}.${{ env.GITHUB_RUN_NUMBER }}-${{ env.GITHUB_RUN_ATTEMPT }}

