name: Makefile CI

on:
  push:
    branches: [ "master" , "github-actions"]
  pull_request:
    branches: [ "master" ]

jobs:
  build-publish:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install Make
      run: make
      
    - name: Make build
      run: make build
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        file: docker/alpine/Dockerfile
        context: .
        push: true
        tags: wqd180067/http-echo:latest
        
  deploy:
  
    runs-on: self-hosted
    
    steps: 
    - uses: actions/checkout@v2

    - name: Trigger deploy
      uses: Consensys/kubernetes-action@master
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
      with:
        args: apply -f ./deployment.yaml
