name: Makefile CI

on:
  push:
    branches: [ "master" , "github-actions"]
  pull_request:
    branches: [ "master" ]

jobs:
  build-publish:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install Make
      run: make
      
    - name: Make Build
      run: make build
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        file: docker/alpine/Dockerfile
        context: .
        push: true
        tags: wqd180067/http-echo:latest
